#!/usr/bin/env bash

# Update package list and install nginx
apt-get -y update
apt-get -y install nginx

# Configure custom HTML file
echo "Hello World!" | tee /var/www/html/index.html > /dev/null

# Check if Nginx is running, and if not, start it
if ! service nginx status >/dev/null 2>&1; then
    service nginx start
fi
