#!/usr/bin/env bash
# Update package list and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
if ! sudo service nginx status > /dev/null; then
    sudo service nginx start
fi
